/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FetchRouteImport } from './routes/fetch'
import { Route as LogIndRouteImport } from './routes/log-ind'
import { Route as PriserRouteImport } from './routes/priser'
import { Route as PrivatlivRouteImport } from './routes/privatliv'
import { Route as ProfilIdRouteImport } from './routes/profil.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FetchRoute = FetchRouteImport.update({
  id: '/fetch',
  path: '/fetch',
  getParentRoute: () => rootRouteImport,
} as any)
const LogIndRoute = LogIndRouteImport.update({
  id: '/log-ind',
  path: '/log-ind',
  getParentRoute: () => rootRouteImport,
} as any)
const PriserRoute = PriserRouteImport.update({
  id: '/priser',
  path: '/priser',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivatlivRoute = PrivatlivRouteImport.update({
  id: '/privatliv',
  path: '/privatliv',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilIdRoute = ProfilIdRouteImport.update({
  id: '/profil/$id',
  path: '/profil/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/fetch': typeof FetchRoute
  '/log-ind': typeof LogIndRoute
  '/priser': typeof PriserRoute
  '/privatliv': typeof PrivatlivRoute
  '/profil/$id': typeof ProfilIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/fetch': typeof FetchRoute
  '/log-ind': typeof LogIndRoute
  '/priser': typeof PriserRoute
  '/privatliv': typeof PrivatlivRoute
  '/profil/$id': typeof ProfilIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/fetch': typeof FetchRoute
  '/log-ind': typeof LogIndRoute
  '/priser': typeof PriserRoute
  '/privatliv': typeof PrivatlivRoute
  '/profil/$id': typeof ProfilIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/fetch' | '/log-ind' | '/priser' | '/privatliv' | '/profil/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/fetch' | '/log-ind' | '/priser' | '/privatliv' | '/profil/$id'
  id:
    | '__root__'
    | '/'
    | '/fetch'
    | '/log-ind'
    | '/priser'
    | '/privatliv'
    | '/profil/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FetchRoute: typeof FetchRoute
  LogIndRoute: typeof LogIndRoute
  PriserRoute: typeof PriserRoute
  PrivatlivRoute: typeof PrivatlivRoute
  ProfilIdRoute: typeof ProfilIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fetch': {
      id: '/fetch'
      path: '/fetch'
      fullPath: '/fetch'
      preLoaderRoute: typeof FetchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/log-ind': {
      id: '/log-ind'
      path: '/log-ind'
      fullPath: '/log-ind'
      preLoaderRoute: typeof LogIndRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/priser': {
      id: '/priser'
      path: '/priser'
      fullPath: '/priser'
      preLoaderRoute: typeof PriserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privatliv': {
      id: '/privatliv'
      path: '/privatliv'
      fullPath: '/privatliv'
      preLoaderRoute: typeof PrivatlivRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil/$id': {
      id: '/profil/$id'
      path: '/profil/$id'
      fullPath: '/profil/$id'
      preLoaderRoute: typeof ProfilIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FetchRoute: FetchRoute,
  LogIndRoute: LogIndRoute,
  PriserRoute: PriserRoute,
  PrivatlivRoute: PrivatlivRoute,
  ProfilIdRoute: ProfilIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
